FROM python:3

LABEL maintainer="npmgrafstats@smilebasti.myhome-server.de"

## setup home folder
RUN mkdir -p /root/.config/NPMGRAF

# Install git and build-essential, clone the repository, build and install grepcidr, then clean up
RUN git clone https://github.com/ryantig/grepcidr.git /opt/grepcidr \
    && cd /opt/grepcidr && make && make install \
    && rm -rf /opt/grepcidr \
    && apt-get remove --purge -y git build-essential \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get remove git build-essential -y\
    && rm -rf /var/cache/apk/* \
    && apt-get autoremove -y && apt-get clean 

COPY requirements.txt /root/.config/NPMGRAF/requirements.txt
RUN pip install --no-cache-dir -r /root/.config/NPMGRAF/requirements.txt

## Copy files
COPY Getipinfo.py /root/.config/NPMGRAF/Getipinfo.py
COPY Internalipinfo.py /root/.config/NPMGRAF/Internalipinfo.py
COPY sendips.sh /root/.config/NPMGRAF/sendips.sh
COPY sendredirectionips.sh /root/.config/NPMGRAF/sendredirectionips.sh
COPY start.sh /root/start.sh

# Make scripts executable
RUN chmod +x /root/.config/NPMGRAF/*.py /root/.config/NPMGRAF/*.sh /root/start.sh

# Set the entry point
ENTRYPOINT ["/root/start.sh"]