{
 "title": "NPM Map Influx v2.3",
 "description": "NginxProxyManager Map with InfluxDB v2.3 powered by https://github.com/smilebasti/npmGrafStats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Real Connections (without monitoring services or internal calls)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "All real Accessed Domains",
   "type": "bargauge",
   "description": "(without monitoring services or internal calls)",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Domain" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r._field == \"Domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
     "select": [
      [
       { "params": [ "Domain" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hits per IP",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "IP" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"IP\")  \r\n  |> group(columns: [\"IP\"])\r\n  |> count()\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> yield(name: \"alias\")\r\n",
     "select": [
      [
       { "params": [ "IP" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hit's in the last ...",
   "type": "stat",
   "description": "(without monitoring services or internal calls)",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r._field == \"IP\")\r\n  |> group(columns: [\"_count\"])\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n  |> count()",
     "select": [
      [
       { "params": [ "IP" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hits per Nation",
   "type": "bargauge",
   "description": "(without monitoring services or internal calls)",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r._field == \"Name\")\r\n  |> group(columns: [\"Name\"])\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n  |> count()",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hits per 1 min",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Domain\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"_time=1m\"])\r\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: false)\r\n  |> yield(name: \"count\")\r\n\r\n\r\n",
     "select": [
      [
       { "params": [ "Domain" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Real Reverse Proxy Domains",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Domain" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r._field == \"Domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
     "select": [
      [
       { "params": [ "Domain" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Real Redirection Domains",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Domain" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\")\r\n  |> filter(fn: (r) => r._field == \"Domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
     "select": [
      [
       { "params": [ "Domain" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  { "title": "World Map", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Real IPs Map Overview (without Monitoring service IPs)",
   "type": "geomap",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "latitude" ], "type": "tag" },
      { "params": [ "longitude" ], "type": "tag" },
      { "params": [ "IP" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r._field == \"IP\")  \r\n  |> group(columns: [\"Longitude\",\"Latitude\",\"IP\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n\r\n",
     "select": [
      [
       { "params": [ "IP" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "counts" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "All Accessed (with monitoring services and internal calls)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Accessed Domains",
     "type": "bargauge",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 58 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "Domain" ], "type": "tag" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"Domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
       "select": [
        [
         { "params": [ "Domain" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Detail overall (with monitoring services and internal calls)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hits per IP",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 55 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "IP" ], "type": "tag" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"IP\")  \r\n  |> group(columns: [\"IP\"])\r\n  |> count()\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> yield(name: \"alias\")\r\n",
       "select": [
        [
         { "params": [ "IP" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Hit's in the last ...",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 7, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"IP\")\r\n  |> group(columns: [\"_count\"])\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n  |> count()",
       "select": [
        [
         { "params": [ "IP" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Hits per Nation",
     "type": "bargauge",
     "gridPos": { "h": 22, "w": 12, "x": 12, "y": 55 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"Name\")\r\n  |> group(columns: [\"Name\"])\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n  |> count()",
       "select": [
        [
         { "params": [ "name" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Hits per 1 min",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 63 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Domain\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"_time=1m\"])\r\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: false)\r\n  |> yield(name: \"count\")\r\n\r\n\r\n",
       "select": [
        [
         { "params": [ "Domain" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         { "params": [ "alias" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Monitoring IPs Map",
     "type": "geomap",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "latitude" ], "type": "tag" },
        { "params": [ "longitude" ], "type": "tag" },
        { "params": [ "IP" ], "type": "tag" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MonitoringRedirIPs\" or r[\"_measurement\"] == \"MonitoringRProxyIPs\")\r\n  |> filter(fn: (r) => r._field == \"IP\")  \r\n  |> group(columns: [\"Longitude\",\"Latitude\",\"IP\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n\r\n",
       "select": [
        [
         { "params": [ "IP" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         { "params": [ "counts" ], "type": "alias" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Reverse Proxy - Monitoring and Internal Domain calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Real Reverse Proxy Domains",
     "type": "bargauge",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "Domain" ], "type": "tag" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r._field == \"Domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
       "select": [
        [
         { "params": [ "Domain" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Internal Reverse Proxy Domains",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "Domain" ], "type": "tag" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"InternalRProxyIPs\")\r\n  |> filter(fn: (r) => r._field == \"Domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
       "select": [
        [
         { "params": [ "Domain" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Monitoring Reverse Proxy Domains",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "Domain" ], "type": "tag" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MonitoringRProxyIPs\")\r\n  |> filter(fn: (r) => r._field == \"Domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
       "select": [
        [
         { "params": [ "Domain" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Redirections - Monitoring and Internal Domain calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Real Redirection Domains",
     "type": "bargauge",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 57 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "Domain" ], "type": "tag" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\")\r\n  |> filter(fn: (r) => r._field == \"Domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
       "select": [
        [
         { "params": [ "Domain" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Internal Redirection Domains",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "Domain" ], "type": "tag" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"InternalRedirIPs\")\r\n  |> filter(fn: (r) => r._field == \"Domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
       "select": [
        [
         { "params": [ "Domain" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Monitoring Redirection Domains",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "Domain" ], "type": "tag" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\")\r\n  |> filter(fn: (r) => r._field == \"Domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
       "select": [
        [
         { "params": [ "Domain" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}