{
 "title": "NPM Map Influx v2.1.1",
 "description": "NginxProxyManager Map with Influx v2.1.1 powered by https://github.com/smilebasti/npmGrafStats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "All Accessed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All Accessed Domains",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Domain" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"Domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
     "select": [
      [
       { "params": [ "Domain" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Detail overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "IP count",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "IP" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"IP\")  \r\n  |> group(columns: [\"IP\"])\r\n  |> count()\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> yield(name: \"alias\")\r\n",
     "select": [
      [
       { "params": [ "IP" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hit's of the last ...",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"IP\")\r\n  \r\n  |> group(columns: [\"_count\"])\r\n\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n  |> count()",
     "select": [
      [
       { "params": [ "IP" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hits per Nation",
   "type": "bargauge",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"Name\")\r\n  \r\n  |> group(columns: [\"Name\"])\r\n\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n  |> count()",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hits per 1 min",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Domain\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"_time=1m\"])\r\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: false)\r\n  |> yield(name: \"count\")\r\n\r\n\r\n",
     "select": [
      [
       { "params": [ "Domain" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reverse Proxy and Redirection Domains",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }
  },
  {
   "title": "Reverse Proxy Domains",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Domain" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r._field == \"Domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
     "select": [
      [
       { "params": [ "Domain" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Redirection Domains",
   "type": "bargauge",
   "description": "If enabeld in settings",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Domain" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\")\r\n  |> filter(fn: (r) => r._field == \"Domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
     "select": [
      [
       { "params": [ "Domain" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  { "title": "World Map", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Map Overview",
   "type": "geomap",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "latitude" ], "type": "tag" },
      { "params": [ "longitude" ], "type": "tag" },
      { "params": [ "IP" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: \"npmgrafstats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"IP\")  \r\n  |> group(columns: [\"Longitude\",\"Latitude\",\"IP\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n\r\n",
     "select": [
      [
       { "params": [ "IP" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "counts" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}