{
 "title": "npmGrafStats Map Dashboard v3.1+ InfluxDBv2 NO filter",
 "description": "npmGrafStats Map Dashboard with InfluxDB powered by https://github.com/smilebasti/npmGrafStats\n\nFor a Dashboard with the filtering option use https://grafana.com/grafana/dashboards/18826",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Overview (without monitoring services or internal calls)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "All real Accessed Domains",
   "type": "bargauge",
   "description": "(without monitoring services or internal calls)",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Domain" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r._field == \"Domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
     "select": [
      [
       { "params": [ "Domain" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hits per IP",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "IP" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"IP\")  \r\n  |> group(columns: [\"IP\"])\r\n  |> count()\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> yield(name: \"alias\")\r\n",
     "select": [
      [
       { "params": [ "IP" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hit's in the last ...",
   "type": "stat",
   "description": "(without monitoring services or internal calls)",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r._field == \"IP\")\r\n  |> group(columns: [\"_count\"])\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n  |> count()",
     "select": [
      [
       { "params": [ "IP" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hits per Nation",
   "type": "bargauge",
   "description": "(without monitoring services or internal calls)",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r._field == \"Name\")\r\n  |> group(columns: [\"Name\"])\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n  |> count()",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hits per 1 min",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Domain\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"_time=1m\"])\r\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: false)\r\n  |> yield(name: \"count\")\r\n\r\n\r\n",
     "select": [
      [
       { "params": [ "Domain" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Real Reverse Proxy Domains",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Domain" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r._field == \"Domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
     "select": [
      [
       { "params": [ "Domain" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Real Redirection Domains",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Domain" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\")\r\n  |> filter(fn: (r) => r._field == \"Domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
     "select": [
      [
       { "params": [ "Domain" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  { "title": "World Map", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Real IPs Map Overview (without excluded IPs)",
   "type": "geomap",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "latitude" ], "type": "tag" },
      { "params": [ "longitude" ], "type": "tag" },
      { "params": [ "IP" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r._field == \"IP\")  \r\n  |> group(columns: [\"longitude\",\"latitude\",\"IP\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n\r\n",
     "select": [
      [
       { "params": [ "IP" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "counts" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Browser and Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Data (lenght) transmitted per Domain (Top 10)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\n  |> filter(fn: (r) => r[\"_field\"] == \"length\")\n  |> group(columns: [\"Domain\"])\n  |> sum()\n  |> group()\n  |> sort(desc: true)\n  |> limit(n: 10)\n  \n  "
    }
   ]
  },
  {
   "title": "Statuscode distribution",
   "type": "piechart",
   "description": " ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\n  |> filter(fn: (r) => r[\"_field\"] == \"statuscode\")\n  |> duplicate(column: \"_value\", as: \"new_column\")\n  |> group(columns: [\"new_column\"])\n  |> count()\n  |> yield(name: \"alias\")"
    }
   ]
  },
  {
   "title": "AbuseIpDB Confidence Score",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\n  |> filter(fn: (r) => r[\"_field\"] == \"abuseConfidenceScore\")\n  |> group(columns: [\"_measurement\", \"abuseConfidenceScore\"])\n  |> count()\n  |> drop(columns: [\"_start\", \"_stop\"])"
    }
   ]
  },
  {
   "title": "Browsers",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\n  |> filter(fn: (r) => r._field == \"browser\")\n  |> duplicate(column: \"_value\", as: \"browser\")\n  |> group(columns: [\"browser\"])\n  |> count()\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\n  \n"
    }
   ]
  },
  {
   "title": "Browser Version",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\n  |> filter(fn: (r) => r._field == \"browser_version\")\n  |> duplicate(column: \"_value\", as: \"browser_version\")\n  |> group(columns: [\"browser_version\"])\n  |> count()\n  |> top(n: 10)\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])"
    }
   ]
  },
  {
   "title": "OS",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\n  |> filter(fn: (r) => r._field == \"os\")\n  |> duplicate(column: \"_value\", as: \"os\")\n  |> group(columns: [\"os\"])\n  |> count()\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\n  \n"
    }
   ]
  },
  { "title": "ASN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "ASN",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Asn\")  \r\n  |> group(columns: [\"Asn\"])\r\n  |> count()\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> yield(name: \"alias\")"
    }
   ]
  },
  {
   "title": "ASN (per IP)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Asn\")  \r\n  |> group(columns: [\"Asn\", \"IP\"])\r\n  |> count()\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> yield(name: \"alias\")"
    }
   ]
  }
 ]
}